### ISSUE TITLE
[BUG] Problem when using SUBFOLDER

### ISSUE THREAD

**Issue by AliM1988** [linuxserver/docker-sqlitebrowser#13]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I used this docker-compose file:

```
---
services:
  sqlitebrowser:
    image: lscr.io/linuxserver/sqlitebrowser:latest
    container_name: sqlitebrowser
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUBFOLDER=/somepath/    # need both slashes IE /subfolder/
    volumes:
      - /root/mydir:/config
    ports:
      - 3000:3000   # HTTP
      - 3001:3001   # HTTPS 
    restart: unless-stopped
```
By navigating to url: {my-mvs-ip}:3000/somepath , I faced this :
![image](https://github.com/user-attachments/assets/a2b54ff4-2cc5-421c-9da3-06719b5fc150)

But if SUBFOLDER don't be used, it works fine.

### Steps To Reproduce

use above docker-compose file

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
use above docker-compose file
```

### Container logs

```bash
sqlitebrowser  | [migrations] started
sqlitebrowser  | [migrations] no migrations found
sqlitebrowser  | ───────────────────────────────────────
sqlitebrowser  | 
sqlitebrowser  |       ██╗     ███████╗██╗ ██████╗
sqlitebrowser  |       ██║     ██╔════╝██║██╔═══██╗
sqlitebrowser  |       ██║     ███████╗██║██║   ██║
sqlitebrowser  |       ██║     ╚════██║██║██║   ██║
sqlitebrowser  |       ███████╗███████║██║╚██████╔╝
sqlitebrowser  |       ╚══════╝╚══════╝╚═╝ ╚═════╝
sqlitebrowser  | 
sqlitebrowser  |    Brought to you by linuxserver.io
sqlitebrowser  | ───────────────────────────────────────
sqlitebrowser  | 
sqlitebrowser  | To support the app dev(s) visit:
sqlitebrowser  | DB Browser for SQLite: https://www.patreon.com/db4s
sqlitebrowser  | 
sqlitebrowser  | To support LSIO projects visit:
sqlitebrowser  | https://www.linuxserver.io/donate/
sqlitebrowser  | 
sqlitebrowser  | ───────────────────────────────────────
sqlitebrowser  | GID/UID
sqlitebrowser  | ───────────────────────────────────────
sqlitebrowser  | 
sqlitebrowser  | User UID:    1000
sqlitebrowser  | User GID:    1000
sqlitebrowser  | ───────────────────────────────────────
sqlitebrowser  | [custom-init] No custom files found, skipping...
sqlitebrowser  | _XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
sqlitebrowser  | 
sqlitebrowser  | Xvnc KasmVNC 1.2.0 - built Jul 13 2024 18:55:13
sqlitebrowser  | Copyright (C) 1999-2018 KasmVNC Team and many others (see README.me)
sqlitebrowser  | See http://kasmweb.com for information on KasmVNC.
sqlitebrowser  | Underlying X server release 12014000, The X.Org Foundation
sqlitebrowser  | 
sqlitebrowser  | [ls.io-init] done.
sqlitebrowser  | Obt-Message: Xinerama extension is not present on the server
sqlitebrowser  | 19
sqlitebrowser  | QStandardPaths: wrong permissions on runtime directory /config/.XDG, 0755 instead of 0700
sqlitebrowser  | MESA: error: ZINK: failed to choose pdev
sqlitebrowser  | glx: failed to create drisw screen
```
