### ISSUE TITLE
Can I specify a database to automatically open?

### ISSUE THREAD

**Issue by halfer** [linuxserver/docker-sqlitebrowser#14]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Hi folks

I'm logging this as a "feature request", but I expect it is already possible. I have scoured the docs fairly thoroughly, and cannot find anything.

I have set up this image in my Docker Compose like so:

```
  db-browser:
    image: lscr.io/linuxserver/sqlitebrowser:latest
    ports:
      - 3000:3000
    environment:
      - FM_HOME=/database
    volumes:
      - ../database:/database
      - ../storage/sqlitebrowser:/config
```

This seems to work great; the `database` volume lets the system read from my SQLite folder. However I'd love to be able to load a database automatically, as for my current project I'll always be working on just one database.

I wonder if it could be this file?

https://github.com/linuxserver/docker-sqlitebrowser/blob/master/root/defaults/autostart

Could I just amend this to have a fully-qualified database pathname, and it would auto-open? I'd need my own Dockerfile so as to make this change, but that is not much bother. (I may yet try this, but it is rather guesswork at this stage).

Thanks for your work - this is going to be very useful!

### Reason for change

I suspect this is not a code change, maybe a documentation change. I think it would be a generally useful feature.

### Proposed code change

Probably a code change is not necessary.
