### ISSUE TITLE
[BUG] Graphics subsystem won't start, "MESA: error: ZINK: failed to choose pdev"

### ISSUE THREAD

**Issue by halfer** [linuxserver/docker-sqlitebrowser#15]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I start sqlitebrowser via Docker, and Nginx reports "502 Bad Gateway" instead of dropping me into the familiar VNC environment. I am not sure what changed. I blatted my on-host `/config` folder in case anything dodgy got in there.

### Expected Behavior

I should see the VNC environment at `localhost:3000`.

### Steps To Reproduce

I pulled the latest image today, and then use the DC config file per the sample here. Since this is in Docker, I am not sure what has changed, I have been using it fine for months.

I am on this version of Docker:

`Docker version 24.0.2, build cb74dfc`.

I was previously using `docker-compose`, but switching to `docker compose` has made no difference.

### Environment

Here is my DC config (db-browser inherits from your image):

```
version: "3"
# The container names help running local/browser-local/browser-contained
# simultaneously without any conflicts.

services:
  web-dev:
    container_name: sequoia-app-local
    # The volume is just for dev
    volumes:
      - ../:/project
    ports:
      - 8000:8000
  web-browser-test:
    container_name: sequoia-app-test-local
    volumes:
      - ../:/project
  selenium:
    container_name: selenium-local
    ports:
      - 4444:4444
    environment:
      # A higher number of sessions locally does seem to help
      - SE_NODE_MAX_SESSIONS=8
      - VNC_NO_PASSWORD=1
  db-browser:
    image: sequoia-db-browser
    ports:
      - 3000:3000
    container_name: db-browser-local
    environment:
      - FM_HOME=/database
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ../database:/database
      - ../storage/sqlitebrowser:/config
```

### CPU architecture

x86-64

### Docker creation

Here is my `Dockerfile`:

```
# This image loads the dev database on start-up
FROM lscr.io/linuxserver/sqlitebrowser:latest

# Improving this hacky fix has been discussed here:
# https://github.com/linuxserver/docker-sqlitebrowser/issues/14, however the better
# solution seems to need to write to the config folder, which is a Docker volume. So
# I am not sure how that could be automated.
#
RUN mv /usr/bin/sqlitebrowser /usr/bin/sqlitebrowser-exec
RUN echo '#!/bin/bash' > /usr/bin/sqlitebrowser
RUN echo '/usr/bin/sqlitebrowser-exec /database/database-dev.sqlite' >> /usr/bin/sqlitebrowser

# I have spotted a permissions oddity, which will cause the sqlite-browser not to
# init properly, and result in '502 Bad Gateway' from Nginx if accessed. Run a
# `docker logs -f db-browser-local` from the Docker host to see relevant logs if
# you get this. However the below seems to squelch the errors:
RUN echo 'chown 911 /config/.XDG' >> /usr/bin/sqlitebrowser
RUN echo 'chmod 0700 /config/.XDG' >> /usr/bin/sqlitebrowser

# There is a separate complaint about creating this folder
RUN echo 'mkdir /tmp/.X11-unix' >> /usr/bin/sqlitebrowser

RUN chmod +x /usr/bin/sqlitebrowser
```

The chowns/chmods etc work at run-time before the server is started up, and they seem to be effective in stopping the errors. But the MESA/ZINK error is still evident.

### Container logs

IMO it's almost certainly the MESA error that is borking things here:

```
jon # docker logs -f db-browser-local 
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support the app dev(s) visit:
DB Browser for SQLite: https://www.patreon.com/db4s

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────
[custom-init] No custom files found, skipping...
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

Xvnc KasmVNC 1.3.3 - built Nov  9 2024 18:55:48
Copyright (C) 1999-2018 KasmVNC Team and many others (see README.me)
See http://kasmweb.com for information on KasmVNC.
Underlying X server release 12014000, The X.Org Foundation

[ls.io-init] done.
Obt-Message: Xinerama extension is not present on the server
MESA: error: ZINK: failed to choose pdev
glx: failed to create drisw screen
```
