### ISSUE TITLE
[BUG] Icons are not showing up

### ISSUE THREAD

**Issue by DaniDipp** [linuxserver/docker-sqlitebrowser#18]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Icons aren't showing up in the interface

![2024-12-28T12-57-32](https://github.com/user-attachments/assets/e0acc639-2a4b-44fd-9e40-a35270d17ff2)
![2024-12-28T12-56-53](https://github.com/user-attachments/assets/0b0a0b79-dd3b-499c-91fb-be9abd782b27)

### Expected Behavior

Icons should be visible

### Steps To Reproduce

1. start contaienr
2. observe buttons

### Environment

```markdown
- OS: Debian GNU/Linux 11 (bullseye) x86_64
- How docker service was installed: via apt
```

### CPU architecture

x86-64

### Docker creation
![screenshot](https://github.com/user-attachments/assets/f76e2516-653c-4466-a2c5-59a5f850093d)

### Container logs

```bash
[migrations] started
[migrations] no migrations found
usermod: no changes
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support the app dev(s) visit:
DB Browser for SQLite: https://www.patreon.com/db4s

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    911
User GID:    911
───────────────────────────────────────
[custom-init] No custom files found, skipping...
[ls.io-init] done.
Openbox-Message: Failed to open the display from the DISPLAY environment variable.
19
Obt-Message: Xinerama extension is not present on the server
 2024-12-28 11:45:30,269 [PRIO] Connections: accepted: @194.36.25.40_1735386330.258035::websocket
 2024-12-28 11:48:19,887 [PRIO] Connections: accepted: @2a02:a448:aa8f:0:8eb:40cf:395f:9a67_1735386499.870804::websocket
 2024-12-28 11:48:21,731 [PRIO] Connections: accepted: @194.36.25.40_1735386501.716439::websocket
 2024-12-28 11:48:24,691 [PRIO] Connections: closed: @194.36.25.40_1735386501.716439::websocket (Clean disconnection)
 2024-12-28 12:02:06,008 [PRIO] Connections: closed: @2a02:a448:aa8f:0:8eb:40cf:395f:9a67_1735386499.870804::websocket (Clean disconnection)
 2024-12-28 12:02:13,633 [PRIO] Connections: accepted: @2a02:a448:aa8f:0:8eb:40cf:395f:9a67_1735387333.621697::websocket
```

**Comment by DaniDipp** [comment]
Let me know if there is anything else I can do to help with debugging this

**Comment by j0nnymoe** [comment]
We don't support portainer for deployment of our containers. You need to provide a valid PUID/PGID.

**Comment by DaniDipp** [comment]
Ok thanks for the quick response. I deleted the container and recreated it with docker compose. I remounted the config folder so the cache in there is the same:
````yaml
version: "3.7"

services:
  sqlite-browser:
    image: linuxserver/sqlitebrowser:latest
    container_name: sqlite-browser
    networks:
         - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.sqlite-browser.rule=Host(`*****`)
      - traefik.http.services.sqlite-browser.loadbalancer.server.port=3000
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - TITLE=Lords of Minecraft Sqlite
      - CUSTOM_USER=staff
      - PASSWORD=*****
    volumes:
      - ./:/config/
      - /home/docker/multicraft/servers/:/multicraft/
networks:
  web:
    external: true
```
